name: hero
description: A new Flutter project.




publish_to: 'none' 


version: 2.11.2+32
#hey idiot did you turn main page timer back on??

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.0
  flutter_bloc: ^7.0.0
  step_progress_indicator: ^1.0.2
  intl: ^0.17.0
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  provider: ^6.0.2
  authentication_repository: ^2.0.0+2
  http: ^0.13.4
  firebase_storage: ^11.0.10
  image_picker: ^0.8.4+2
  firebase_crashlytics: ^3.0.11
  firebase_analytics: ^10.1.0
  typesense: ^0.2.0
  uuid: ^3.0.6
  like_button: ^2.0.4
  fl_chart: ^0.55.0
  firebase_messaging: ^14.2.1
  url_launcher: ^6.1.5
  cached_network_image: ^3.2.1
  new_version: ^0.3.1
  flutter_image_compress: ^1.1.3
  path_provider: ^2.0.11
  collection: ^1.16.0
  timeago: ^3.3.0
  percent_indicator: ^4.2.2
  tweet_ui: ^4.0.4
  photo_view: ^0.13.0
  awesome_dialog: ^3.0.2
  fake_cloud_firestore: ^2.3.0
  firebase_storage_mocks: ^0.6.0
  font_awesome_flutter: ^10.3.0
  rive: ^0.9.1
  cool_dropdown: ^1.4.2
  flutter_svg: ^1.1.6
  dropdown_textfield: ^1.0.7
  flutter_native_splash: ^2.2.9
  flutter_launcher_icons: ^0.11.0
  bloc_test: ^8.5.0
  mockito: ^5.3.2
  flutter_staggered_grid_view: ^0.6.2
  camera: ^0.10.1
  shared_preferences: ^2.0.16
  firebase_app_check: ^0.1.1+8
  image_editor: ^1.3.0
  image_editor_plus: ^0.1.8
  dice_bear: ^0.1.5
  vibration: ^1.7.6
  chewie: ^1.4.0
  video_player: ^2.5.1
  video_compress: ^3.1.2
  
  cached_video_player: ^2.0.3
  flutter_cache_manager: ^3.3.0
  gallery_saver: ^2.3.2
  
  image_cropper: ^3.0.1
  
  video_trimmer: ^2.0.1
  flutter_countdown_timer: ^4.1.0
  shimmer: ^2.0.0
  flutter_animate: ^4.1.0
  carousel_slider: ^4.2.1
  optimized_cached_image: ^3.0.1
  
  
  
  
  






  

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/stingray_general/stingray_new_logo.png"
  remove_alpha_ios: true


flutter_native_splash: 
  image: assets/stingray_logo.png
  color: "#000000"

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.4
  isar_generator: ^3.0.2
  build_runner: any
  test: ^1.21.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/valentine.png
     - assets/smugg.png
     - assets/stingray_logo.png
     - assets/smugug.png
     - assets/red_flag.gif
     - assets/skyrim.webp
     - assets/ryuk.webp
     - assets/riv/
     - assets/genders/
     - assets/social_media/
     - assets/stingray_general/
     - assets/tutorial/


