// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIqD9WlqoNEw6RIgfPlpcMj0Fsa51oTvI',
    appId: '1:180621444285:web:28408d411cdd6fc554a3d4',
    messagingSenderId: '180621444285',
    projectId: 'hero-cbfc8',
    authDomain: 'hero-cbfc8.firebaseapp.com',
    databaseURL: 'https://hero-cbfc8-default-rtdb.firebaseio.com',
    storageBucket: 'hero-cbfc8.appspot.com',
    measurementId: 'G-EQR3N1Y646',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa9y_okXGZFegPic-548SVrm3KWqn6MTE',
    appId: '1:180621444285:android:a9429b5acc2c54bf54a3d4',
    messagingSenderId: '180621444285',
    projectId: 'hero-cbfc8',
    databaseURL: 'https://hero-cbfc8-default-rtdb.firebaseio.com',
    storageBucket: 'hero-cbfc8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJG97JW66IqQNgQwj-83yFG83_L7wN6kk',
    appId: '1:180621444285:ios:3d025739e6f81f2b54a3d4',
    messagingSenderId: '180621444285',
    projectId: 'hero-cbfc8',
    databaseURL: 'https://hero-cbfc8-default-rtdb.firebaseio.com',
    storageBucket: 'hero-cbfc8.appspot.com',
    androidClientId: '180621444285-mr69ltpgkeqi58butndse691i067ou04.apps.googleusercontent.com',
    iosClientId: '180621444285-ssquf5sfoluqa2n6hlec4njfbc1bde60.apps.googleusercontent.com',
    iosBundleId: 'com.matoitechnology.fishtank1256456456',
  );
}
